"""first

Revision ID: 5b8417f0df04
Revises: 
Create Date: 2024-10-03 14:03:45.461146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8417f0df04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('months_old', sa.Integer(), nullable=False),
    sa.Column('descriptions', sa.String(), nullable=False),
    sa.Column('id_breed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_breed'], ['breed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cats')
    op.drop_table('breed')
    # ### end Alembic commands ###
