"""first

Revision ID: 74ccb4fd4fe6
Revises: 
Create Date: 2024-10-04 12:26:04.302356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ccb4fd4fe6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('months_old', sa.Integer(), nullable=False),
    sa.Column('descriptions', sa.String(), nullable=False),
    sa.Column('breed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['breed_id'], ['breed.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cat')
    op.drop_table('breed')
    # ### end Alembic commands ###
